#ifndef CONTAINER_VERSION_H_
#define CONTAINER_VERSION_H_

#define CONTAINER_VERSION "0.1.0"

#define CONTAINER_MAJOR_VERSION 0
#define CONTAINER_MINOR_VERSION 1
#define CONTAINER_PATCH_VERSION 0

#endif  // CONTAINER_VERSION_H_

