name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
          pip install sphinx sphinx-rtd-theme breathe myst_parser breathe sphinx_design pydata-sphinx-theme
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.install-dependencies.outputs.path }}
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-  
      
      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
          
      - name: Cache documentation
        uses: actions/cache@v2
        with:
          path: ${{ steps.build-docs.outputs.path }}
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/**/*') }}
          restore-keys: |
            ${{ runner.os }}-docs-

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # path to index!
          publish_dir: docs/build/html
