name: Build Documentation

# This configuration will trigger the workflow when a push event 
# is made on the main branch, and the commit contains a change in 
# a markdown file and when a pull request event occurs with "updated docs" label.
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    types: [labeled]
    labels:
      - updated docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.install-dependencies.outputs.path }}
          key: install-dependencies-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            install-dependencies-  
      
      - name: Install dependencies
        id: install-dependencies
          sudo apt-get update
        run: |
          sudo apt-get install -y doxygen doxygen-doc doxygen-latex doxygen-gui graphviz
          pip install sphinx sphinx-rtd-theme breathe myst_parser breathe sphinx_design pydata-sphinx-theme
      
      - name: Cache documentation
        uses: actions/cache@v2
        with:
          path: ${{ steps.build-docs.outputs.path }}
          key: build-docs-${{ hashFiles('docs/**/*') }}
          restore-keys: |
            build-docs-

      - name: Build documentation
        id: build-docs
        run: | 
          echo "Generate doxygen xml for breathe to understand the source code"
          doxygen Doxyfile
          echo "build the documentation"
          cd docs
          make html


      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # path to index!
          publish_dir: docs/build/html
