name: cppcheck-action
on:
  workflow_run:
    workflows: ["CMake Build Matrix"]
    branches: [main]
    types: 
      - completed


jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          other_options: -i ./build -i ./examples -i ./libs -i ./scripts -v
      
      - name: display report
        run:  |
          cat cppcheck_report.txt

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'